# Distributor Node (Argus)
version: '3.4'
services:
  distributor:
    image: joystream/distributor-node:1.2.0
    container_name: distributor
    restart: on-failure
    volumes:
      - ./distributor/keystore:/keystore
      - ./distributor/config/config.yml:/joystream/distributor-node/config.yml
      - ./distributor/data:/data
      - ./distributor/cache:/cache
      - ./distributor/logs:/logs
      - ./distributor/scratch:/scratch
    working_dir: /joystream/distributor-node
    ports:
      - 3334:3334
      - 127.0.0.1:3335:3335
    entrypoint: ['yarn', 'joystream-distributor']
    command: ['start']