# Distributor Node (Argus)
version: '3.4'
services:
  distributor:
    image: joystream/distributor-node:1.2.1
    container_name: distributor
    restart: on-failure
    volumes:
      - ./distributor/keystore:/keystore
      - ./distributor/data:/data
      - ./distributor/cache:/cache
      - ./distributor/logs:/logs
      - ./distributor/scratch:/scratch
      - ./distributor/config/config.yml:/joystream/distributor-node/config.yml:ro
      - ./distributor-runner.sh:/joystream/distributor-node/runner.sh:ro
    working_dir: /joystream/distributor-node
    ports:
      - 127.0.0.1:3334:3334 # Public API
      - 127.0.0.1:3335:3335 # Private node operator API
    environment:
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-no}
      OTEL_APPLICATION: distributor-node
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
      OTEL_RESOURCE_ATTRIBUTES: service.name=argus,deployment.environment=production
    entrypoint: ['/joystream/distributor-node/runner.sh']
    command: ['start']