# StorageNode (colossus)
version: '3.4'
services:
  colossus:
    image: joystream/storage-node:3.4.0
    container_name: colossus
    restart: unless-stopped
    volumes:
      - ./storage/data:/data
      - ./storage/keystore:/keystore
      - ./storage/logs:/logs
    working_dir: /joystream/storage-node
    ports:
      - 3333:3333
    entrypoint: sh
    command: -c "
      yarn storage-node server
      --worker 0
      --port 3333
      --uploads /data
      --sync
      --syncInterval 1
      --syncWorkersNumber 20
      --queryNodeEndpoint http://graphql-server:${GRAPHQL_SERVER_PORT}/graphql
      --apiUrl ${JOYSTREAM_NODE_WS}
      --logFilePath /logs
      --logFileChangeFrequency none
      --keyFile /keystore/keyfile.json
      "