# StorageNode (Colossus)
version: '3.4'
services:
  storage:
    image: joystream/storage-node:3.5.0
    container_name: storage
    restart: unless-stopped
    volumes:
      - ./storage/data:/data
      - ./storage/keystore:/keystore
      - ./storage/logs:/logs
      - ./storage-runner.sh:/joystream/storage-node/runner.sh:ro
    working_dir: /joystream/storage-node
    ports:
      - 3333:3333
    environment:
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-no}
      OTEL_APPLICATION: storage-node
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
      OTEL_RESOURCE_ATTRIBUTES: service.name=storage-node,deployment.environment=production
    entrypoint: ['/joystream/storage-node/runner.sh']
    command: "
      server
      --worker 0
      --port 3333
      --uploads /data
      --sync
      --syncInterval 1
      --syncWorkersNumber 20
      --queryNodeEndpoint http://graphql-server:${GRAPHQL_SERVER_PORT}/graphql
      --apiUrl ${JOYSTREAM_NODE_WS}
      --logFilePath /logs
      --logFileChangeFrequency none
      --keyFile /keystore/keyfile.json
      "
