# Caddy
version: '3.4'
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./config:/config
      - ./data:/data
    environment:
      DOMAIN: ${CADDY_DOMAIN}
      EMAIL: ${CADDY_EMAIL}
      LOG_FILE: /data/access.log
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://collector:4317/
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: caddy
